export const GET_COUNTRIES_BY_LONGNAME = 'GET_COUNTRIES_BY_LONGNAME'
export const GET_COUNTRIES_BY_SHORTNAME = 'GET_COUNTRIES_BY_SHORTNAME'
export const GET_COUNTRIES_BY_CODE = 'GET_COUNTRIES_BY_CODE'
export const GET_COUNTRIES_BY_CURRENCY = 'GET_COUNTRIES_BY_CURRENCY'